### PR TITLE
Multiple grammar fixes.

### PR DESCRIPTION
**Pull request by bepnewt**

### CODE REVIEW

**Comment by ismcagdas** [comment]
@bepnewt thank you for your contribution. I think it is better to redirect developer to a document like this one https://en.wikipedia.org/wiki/Multitenancy if developer doesn't know multi tenancy.

So, instead of using " If you don't understand multi-tenancy", we can use something like this;

> If you don't have an idea about Multi-Tenancy, you can read https://en.wikipedia.org/wiki/Multitenancy. If you don't want to create a multi-tenant application, you can **disable** it .....

What do you think ?

**Comment by bepnewt** [comment]
That is a good solution.

-BEP

**Comment by ismcagdas** [comment]
@bepnewt can you update the PR if you have time ? If not, we can also do it.

**Comment by ismcagdas** [comment]
@bepnewt thanks a lot 😄 .

**Pull request merged**
